#!/bin/bash
set -e

cat .io.livecode.ch/header.txt $1 .io.livecode.ch/footer.txt >out.scm
echo '(load "mk/mk.scm")' >load.scm
if [ -s $2 ]
then
    mv $2 extra.scm
else
    touch extra.scm
fi
cat load.scm extra.scm out.scm >script.scm

cd src

scheme mk/mk.scm --script ../script.scm
